# Numpy

NumPy documentation:
https://numpy.org/doc/stable/

## Создание массива

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
python_list = [0, 1, 2, 3]

In [ ]:
# Так создавать numpy-массив нельзя
wrong_numpy_array = np.array(0, 1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

* из списков или кортежей Python

In [ ]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
type(a)

In [ ]:
python_list = [0, 1, 2, 3]
a = np.array(python_list)
a

array([0, 1, 2, 3])

In [ ]:
python_tuple = (0, 1, 2, 3)
a = np.array(python_tuple)
a

array([0, 1, 2, 3])

* многомерные массивы

In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.shape

(4,)

In [ ]:
b.shape

(2, 3)

<img src=https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays-1024x572.png width="600">

* нулевой массив

In [ ]:
a = np.zeros((1, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.zeros((4, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* единичный массив

In [ ]:
a = np.ones((1, 10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
a = np.ones((4, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* пустой массив со случайным заполнением

In [ ]:
a = np.empty((5, 4))
a

array([[0. , 0. , 0.3, 1. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0. , 0. , 1. ],
       [0.5, 0. , 0. , 1. ]])

* массив такой же формы

In [ ]:
b = np.zeros_like(a)
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b.shape

(5, 4)

* массив из последовательности

In [ ]:
# arange([start,] stop[, step,], dtype=None)
a = np.arange(0, 10, 0.78)
a

array([0.  , 0.78, 1.56, 2.34, 3.12, 3.9 , 4.68, 5.46, 6.24, 7.02, 7.8 ,
       8.58, 9.36])

какой будет последний элемент в массиве ниже?

In [ ]:
a = np.arange(0, 10, 0.5)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
a = np.linspace(0, 99, num=15) # 15 значений с равными интервалами
a

array([ 0.        ,  7.07142857, 14.14285714, 21.21428571, 28.28571429,
       35.35714286, 42.42857143, 49.5       , 56.57142857, 63.64285714,
       70.71428571, 77.78571429, 84.85714286, 91.92857143, 99.        ])

In [ ]:
a.shape

(15,)

In [ ]:
np.linspace endpopint

In [ ]:
a = np.linspace(0,99,num=15, endpoint=False) # 15 равных значений
a

array([ 0. ,  6.6, 13.2, 19.8, 26.4, 33. , 39.6, 46.2, 52.8, 59.4, 66. ,
       72.6, 79.2, 85.8, 92.4])

In [ ]:
a = np.linspace(0,99,num=15, endpoint=True) # 15 равных значений
a

array([ 0.        ,  7.07142857, 14.14285714, 21.21428571, 28.28571429,
       35.35714286, 42.42857143, 49.5       , 56.57142857, 63.64285714,
       70.71428571, 77.78571429, 84.85714286, 91.92857143, 99.        ])

In [ ]:
a = np.linspace(0, 99, num=101, dtype=int, endpoint=True) # dtype - тип данных
a

array([ 0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a = np.linspace(0, 99, num=101, dtype=int, endpoint=False) # dtype - тип данных
a

array([ 0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
a = np.linspace(0, 99, num=10)
a

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [ ]:
a = np.logspace(1, 3, 3, base=10)
a

array([  10.,  100., 1000.])

#### сравним скорость вычислений типов list и numpy.ndarray

In [ ]:
%timeit [i**2 for i in range(1000)]

In [ ]:
%timeit np.arange(1000)**2

## Типы данных

https://numpy.org/doc/stable/user/basics.types.html

* тип данных по-умолчанию

In [ ]:
a = np.array([0, 1, 2, 3])

In [ ]:
a.dtype

In [ ]:
a = np.array([1.3, 0.5, 4])
a.dtype

In [ ]:
a = np.array([1+2j, 3+4j, 5+6*1j])
a.dtype

dtype('complex128')

In [ ]:
a = np.array([True, False, False, True])
a.dtype

dtype('bool')

In [ ]:
a = np.array([0.25, 0.5, 4]) # строковый тип данных
a.dtype

dtype('float64')

In [ ]:
a

array([0.25, 0.5 , 4.  ])

In [ ]:
a = np.array(['Bonjo12345werwer67', 'Hello', 'Hallo',])
a.dtype

In [ ]:
a1 = 12313241545646848648645645645645412786873132156465456465464

In [ ]:
a = np.array(a1)
a.dtype # object

In [ ]:
np.iinfo(int) # Bounds of the default integer on this system.

In [ ]:
np.iinfo(np.int32) # Bounds of a 32-bit integer

In [ ]:
np.iinfo(np.int64) # Bounds of a 64-bit integer

* явное указание типа данных

In [ ]:
a = np.array([0, 1, 2, 3], dtype=np.int8)
a.dtype

In [ ]:
a

In [ ]:
a = np.array([0, 1, 2, 3, -1], dtype=np.bool)
a # все, что <> 0 - False

In [ ]:
a = np.array([1.3, 0.8, 4], dtype=np.int8)
a

In [ ]:
a = np.array(['dgf', 0.5, 4], dtype=np.int8)

In [ ]:
a = np.array(['dgf', 0.5, 4], dtype=np.bool)
a

In [ ]:
a = np.array(['7', 0.5, 4], dtype=np.int8)

In [ ]:
a

In [ ]:
a = np.array(['7.2', 0.5, 4], dtype=np.float)
a

* None и np.nan

In [ ]:
None is None # Замена для `id(None) == id(None)`

In [ ]:
None == None, None is None

In [ ]:
np.nan == np.nan, np.nan is np.nan

In [ ]:
np.nan is None, np.nan == None

In [ ]:
type(np.nan)

In [ ]:
type(None)

In [ ]:
np.isnan(np.nan)

In [ ]:
np.isnan(None)

In [ ]:
a = np.array([0,1,np.nan,3])
b = np.array([0,1,2,3])

In [ ]:
c = a+b
c

In [ ]:
a = np.array([0,1,None,3])
b = np.array([0,1,2,3])

In [ ]:
a+b

In [ ]:
a = np.array([0,1,np.nan,3])
a.dtype

## Индексирование

<img src=https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172112.png width="400">

* одномерный массив

In [ ]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a[0]

np.int64(10)

In [ ]:
a[5]

np.int64(15)

In [ ]:
a[9]

np.int64(19)

In [ ]:
# [start:end:step]
a[1:6]

array([11, 12, 13, 14, 15])

In [ ]:
a[1:6:2]

array([11, 13, 15])

In [ ]:
a[:6]

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[6:]

array([16, 17, 18, 19])

In [ ]:
a[:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a[-1]

np.int64(19)

In [ ]:
a[-2]

np.int64(18)

In [ ]:
a[-10]

In [ ]:
a[10]

In [ ]:
a[::-1]

In [ ]:
a[::-2]

In [ ]:
a

In [ ]:
a[-1:-5:-1]

* многомерный массив

<img src=https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172114.png width="400">

In [ ]:
a = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a.shape

(4, 3)

In [ ]:
a[2,1]

np.int64(7)

In [ ]:
a[2]

array([6, 7, 8])

In [ ]:
a[:,1]

array([ 1,  4,  7, 10])

In [ ]:
a[1:, 2]

array([ 5,  8, 11])

In [ ]:
a[1:3,1:3]

In [ ]:
a

In [ ]:
a[::-1]

## Изменение размерности

In [ ]:
a = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a.shape

In [ ]:
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a

In [ ]:
a.reshape((6,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
a.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a.shape

(4, 3)

In [ ]:
a.resize((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

In [ ]:
a.reshape(-1,6)

In [ ]:
a.reshape(-1,5)

In [ ]:
a

In [ ]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a = np.ones((1, 2, 3, 4))

In [ ]:
a.shape

(1, 2, 3, 4)

In [ ]:
a

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a.T.shape

(4, 3, 2, 1)

## Рандом

In [ ]:
# uniform in [0, 1)
a = np.random.rand(4, 4)
a

In [ ]:
# uniform in [0, 5)
a = 5 * np.random.rand(4, 4)
a

In [ ]:
# Gaussian ("standard normal" distribution)
b =  np.random.randn(4,4)
b

In [ ]:
# Gaussian ("standard normal" distribution)
b =  5 * np.random.randn(4,4) + 1
b

In [ ]:
# Integer uniform
c = np.random.randint(0, 10, 10)
c

* фиксация рандома

In [ ]:
import numpy as np

In [ ]:
np.random.seed(123)

In [ ]:
np.random.randn(3)

In [ ]:
np.random.randn(4)

In [ ]:
from numpy.random import MT19937
from numpy.random import RandomState, SeedSequence

In [ ]:
rs = RandomState(MT19937(SeedSequence(123456789))) # более сложная фиксация данных

In [ ]:
rs.randn(3)

In [ ]:
rs.randn(4)

## Выбор по условию (маски)

In [ ]:
np.random.seed(3)
a = np.random.randint(0, 20, 15)
a

In [ ]:
a[a > 10]

In [ ]:
mask = a>10
mask

In [ ]:
a[mask]

In [ ]:
a

In [ ]:
mask = (a>5) & (a<10)
a[mask]

In [ ]:
mask = (a % 3 == 0)
print(mask)
extract_from_a = a[mask]
extract_from_a

In [ ]:
a

In [ ]:
a[a % 3 == 0] = -1
a

In [ ]:
a[0] = 100

In [ ]:
a

In [ ]:
a[:3] = 100

In [ ]:
a

In [ ]:
a = np.array([[0,1,2],[3,4,5],[5,6,7],[8,9,10]])
a

In [ ]:
def flt(a):
    return a>5;

In [ ]:
a[flt(a)]

## Математические операции

* одномерные массивы

In [ ]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

In [ ]:
a

In [ ]:
b

In [ ]:
a + 5

In [ ]:
a * 5

In [ ]:
a - b

In [ ]:
a + b

In [ ]:
a * b

In [ ]:
a / b

In [ ]:
a ** b

* многомерные массивы

In [ ]:
A = np.array([[10,20],[30,40]])
B = np.array([[1,2],[3,4]])

In [ ]:
A

In [ ]:
B

In [ ]:
A - B

In [ ]:
A + B

In [ ]:
A * B

In [ ]:
A / B

In [ ]:
A ** B

In [ ]:
A.dot(B)

In [ ]:
C = np.array([[1,2],[3,4],[5,6]])
C

In [ ]:
A.dot(C)

* использование функций

In [ ]:
a

In [ ]:
a.sum(), np.sum(a)

In [ ]:
a.prod(), np.prod(a) # умножение всех элементов

In [ ]:
np.sqrt(a)

In [ ]:
np.log(a)

In [ ]:
a.min(), a.max()

In [ ]:
a.mean(), np.mean(a)

In [ ]:
np.median(a)

In [ ]:
a.std(), np.std(a)

In [ ]:
a

In [ ]:
a.argmin(), a.argmax()

## Другие полезные функции

In [ ]:
a

* проверка вхождения в массив

In [ ]:
2 in a

In [ ]:
20 in a

* преобразование в список

In [ ]:
a.tolist()

* сортировка списка

In [ ]:
a = np.array([40,10,20,5])
a

In [ ]:
a.sort()

In [ ]:
a

* заполение массива одинаковым значением

In [ ]:
a

In [ ]:
a.fill(7)

In [ ]:
a

## Копирование

In [ ]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
a

In [ ]:
b = a
b

In [ ]:
a[1,1] = 555

In [ ]:
a

In [ ]:
b

In [ ]:
a is b

In [ ]:
id(a), id(b)

In [ ]:
b = a.copy()

In [ ]:
a is b

In [ ]:
id(a), id(b)

In [ ]:
a

In [ ]:
b

In [ ]:
a[1,1] = 5
a

In [ ]:
b